services:
  psql_bp:
    image: postgres:13.22-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  redis:
    image: redis:8.2.0-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}


volumes:
  psql_volume_bp: